### ISSUE TITLE
terrafrom init getting alert. 

### ISSUE THREAD

**Issue by bholagond** [Invicton-Labs/terraform-aws-replicated-secret#1]
An argument named "region" is not expected here.

PS C:\ terraform.exe plan

Error: Iteration over null value

  on outputs.tf line 24, in output "replica_arns":
  23:   value = merge({
  24:     for replica in var.replica_regions :
  25:     replica.region => "arn:${data.aws_arn.secret.partition}:${data.aws_arn.secret.service}:${replica.region}:${data.aws_arn.secret.account}:${data.aws_arn.secret.resource}"
  26:     }, {
    |----------------
    | var.replica_regions is null

A null value cannot be used as the collection in a 'for' expression.

**Comment by KyleKotowick** [comment]
Sorry for the very delayed reply. This functionality is now supported natively in the [`aws_secretsmanager_secret`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/secretsmanager_secret) (see the `replica` block), so this repository will be archived with no further changes.
